# Generated by Django 4.2.9 on 2025-07-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_alter_thermaltolerance_abs_thermal_tolerance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_thermal_limit', models.FloatField(blank=True, null=True)),
                ('rel_thermal_limit', models.FloatField(blank=True, null=True)),
                ('_sst_clim_mmm', models.FloatField(blank=True, null=True)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_limits', to='projects.colony')),
                ('observations', models.ManyToManyField(related_name='thermal_limits', to='projects.observation')),
            ],
        ),
        migrations.CreateModel(
            name='BreakpointTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_breakpoint_temperature', models.FloatField(blank=True, null=True)),
                ('rel_breakpoint_temperature', models.FloatField(blank=True, null=True)),
                ('_sst_clim_mmm', models.FloatField(blank=True, null=True)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakpoint_temperatures', to='projects.colony')),
                ('observations', models.ManyToManyField(related_name='breakpoint_temperatures', to='projects.observation')),
            ],
        ),
    ]
