# Generated by Django 4.2.9 on 2025-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_thermallimit_breakpointtemperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakpointtemperature',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='breakpointtemperature',
            name='timepoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thermallimit',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thermallimit',
            name='timepoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thermaltolerance',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thermaltolerance',
            name='timepoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='breakpointtemperature',
            unique_together={('colony', 'condition', 'timepoint', 'abs_breakpoint_temperature')},
        ),
        migrations.AlterUniqueTogether(
            name='thermallimit',
            unique_together={('colony', 'condition', 'timepoint', 'abs_thermal_limit')},
        ),
        migrations.AlterUniqueTogether(
            name='thermaltolerance',
            unique_together={('colony', 'condition', 'timepoint', 'abs_thermal_tolerance')},
        ),
    ]
