# Generated by Django 4.2.9 on 2025-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_breakpointtemperature_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='timepoint',
            field=models.CharField(max_length=100),
        ),
    ]
