# Generated by Django 4.2.9 on 2025-07-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_alter_observation_timepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakpointtemperature',
            name='timepoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thermallimit',
            name='timepoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thermaltolerance',
            name='timepoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
