# Generated by Django 4.2.9 on 2025-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_alter_breakpointtemperature_timepoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='country',
            field=models.CharField(max_length=10),
        ),
    ]
