# Generated by Django 4.2.9 on 2025-08-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0043_alter_colony_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Filter Group', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter_params', models.JSONField(blank=True, default=dict)),
                ('colonies', models.ManyToManyField(related_name='cart_groups', to='projects.colony')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colony_data', models.JSONField(default=dict)),
                ('cart_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='projects.cartgroup')),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='projects.colony')),
            ],
        ),
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
