# Generated by Django 4.2.9 on 2025-12-13 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0044_cartgroup_cartitem_delete_usercart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectED50Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxplot_image', models.ImageField(blank=True, help_text='ED50s Boxplot', null=True, upload_to='ed50_attachments/boxplots/')),
                ('temperature_curve_image', models.ImageField(blank=True, help_text='Temperature Response Curves', null=True, upload_to='ed50_attachments/temp_curves/')),
                ('model_curve_image', models.ImageField(blank=True, help_text='Model Curve with ED bands', null=True, upload_to='ed50_attachments/model_curves/')),
                ('aggregated_statistics', models.JSONField(blank=True, default=list, help_text='Aggregated Statistics (Mean, SD, SE, Conf_Int for ED5, ED50, ED95)')),
                ('individual_eds', models.JSONField(blank=True, default=list, help_text='Individual ED values')),
                ('calculation_params', models.JSONField(blank=True, default=dict, help_text='Parameters used for calculation (grouping, formula, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ed50_attachments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed50_attachments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project ED50 Attachment',
                'verbose_name_plural': 'Project ED50 Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
