# Generated by Django 4.2.9 on 2026-01-23 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_cartgroup_cartitem_delete_usercart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxplot', models.ImageField(blank=True, null=True, upload_to='attachments/')),
                ('temp_curve', models.ImageField(blank=True, null=True, upload_to='attachments/')),
                ('model_curve', models.ImageField(blank=True, null=True, upload_to='attachments/')),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
                ('statistics', models.JSONField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='attachments/')),
                ('other_photos', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project')),
            ],
        ),
    ]
