# Generated by Django 4.2.9 on 2025-12-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_projected50attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projected50attachment',
            name='description',
            field=models.TextField(blank=True, help_text='HTML description for the attachment', null=True),
        ),
    ]
