# Generated by Django 4.2.9 on 2026-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_add_attachment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='doi',
        ),
        migrations.AddField(
            model_name='attachment',
            name='publications',
            field=models.ManyToManyField(blank=True, help_text='Related publications (can be multiple)', related_name='attachments', to='projects.publication'),
        ),
    ]
