# Generated by Django 4.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_attachment_publications_replace_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='additional_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
