# Generated by Django 4.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_attachment_additional_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
