services:

  database:
    image: postgres:15.3
    restart: unless-stopped
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django-app:
    build:
      context: ./django_app
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - SQL_ENGINE=${SQL_ENGINE}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CONTACT_EMAIL_ADDRESS=${CONTACT_EMAIL_ADDRESS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
      - ./django_app:/usr/src/app
      - ./shared_data:/shared_data
    depends_on:
      - database

  # react-app:
  #   build:
  #     context: ./react_app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

  ed50-fastapi:
    build:
      context: ./ed50-fastapi
      dockerfile: Dockerfile
      # use cache for faster builds
      cache_from:
        - python:3.11-slim
        - continuumio/miniconda3:4.12.0
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - SHARED_DATA_PATH=/shared_data
    volumes:
      - ./ed50-fastapi:/app
      - ./ed50-calculator/examples:/app/data/examples:ro
      - ./shared_data:/shared_data
    depends_on:
      - database

volumes:
  postgres_data: