# Generated by Django 4.2.9 on 2026-05-01 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, default='', max_length=60)),
                ('third_name', models.CharField(blank=True, default='', max_length=60)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('description', models.TextField(blank=True, default='')),
                ('affiliation', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('orcid', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('google_scholar', models.URLField(blank=True, default='')),
                ('researchgate', models.URLField(blank=True, default='')),
                ('research_interests', models.JSONField(blank=True, default=list)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
