# Generated by Django 4.2.9 on 2026-05-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='researcherprofile',
            name='third_name',
        ),
    ]
